### PR TITLE
Setup django debug toolbar

### PR DESCRIPTION
**Pull request by httpdss**
what i did:
* install and configure the django debug toolbar for debugging and development of archerysec
* default DEBUG setting to False and set to True on local_settings file if needed

### CODE REVIEW

**Comment by anandtiwarics** [comment]
@httpdss is it possible for you to update README for development and production installation?

**Comment by anandtiwarics** [comment]
Hi @httpdss 404 error for all static file in docker after implementation of debug toolbar. Could you please check issue #94 ?

**Comment by httpdss** [comment]
@anandtiwarics shouldnt be happening this. have you created a local_settings.py file from the sample? 
im working on the docker stuff and settings to be more intuitive, but should go up without any problem
i'll check other ways until i can reproduce this. 
btw, is the INTERNAL_IPS set correctly to match you ip? (local_settings.py should have this correctly set

**Comment by anandtiwarics** [comment]
@httpdss Yes. It should be work. But we need to create a document before implement this in the project, as many people do not want to do manual stuff. We'll check this later. 
BTW, good idea to have debug toolbar for contributors.

**Comment by httpdss** [comment]
@anandtiwarics perfect! yes, this will be solved on my next PR

**Pull request merged**
