### PR TITLE
Propose another scan type to the project (nmap+vulners API)

### PR DESCRIPTION
**Pull request by GMedian**
This pull request proposes another type of nmap scan using the Vulners dot com API.

- The used NSE script is the lates one from the official repo (https://github.com/vulnersCom/nmap-vulners). It is open and free to use, so it suites perfectly the whole ArcherySec idea.

- In order not to be intrusive I have implemented everything in a most independent way: most of the changes are in separate files, the main project files are untouched.

- Following the general idea of being non-disturbing I have added a separate table (yet with a foreign key to an old one)

NB: This scan type does make many requests to a 3rd party resource (vulners dot com), yet it does include a disclaimer and does not collect much information about the users, so there is no concern of privacy violation.

### CODE REVIEW

**Comment by GMedian** [comment]
By the way, I have noticed some deviations from the existing way to work with a DB in my code. Yet the general idea must be still correct.

Should we agree on accepting the request we might implement the required changes for everything to be in a common way.

**Comment by GMedian** [comment]
I have added some changes to correspond to your general DB model. Now everything except for some possible minor changes should be in place.

**Comment by anandtiwarics** [comment]
Hi @GMedian,

Thanks for the contribution and implemented a great idea for nmap scans. I walk through your code and ran some scan but not able to fetch any data in nmap_vulners module. 

I'm not sure what wrong with my implementation. Could you please, explain or create a small video or will work together to implement this nice feature in Archery. You can contact me on skype : anandtiwarics. 

Thanks.

**Comment by GMedian** [comment]
Hi @anandtiwarics,

Great to hear you might be interested in my work. The main reason you may fail to see any result is that you are scanning against some host nmap_vulners is unable to process efficiently (it can not specify any known vulnerabilities). Here is an example of a valid result:

nmap_vulners_scan

nmap_vulners_result

**Comment by anandtiwarics** [comment]
Hi @GMedian,

Got it.

 I ran some scans on vulnerable vm and seems that vulners NSE script not able to effectively searching potential vulnerable s/w vulnerabilities.

Nmap scan found http version 1.1, but nse script not able to fetch and parse from vulners API.

vulnrs

I'm able to grab data from vulners API for the same version.

https://vulners.com/api/v3/burp/software/?software=http&version=1.1&type=cpe

Manual NSE Script ran:

nse

Please have a look and let me know your thoughts.

**Comment by GMedian** [comment]
Hi!
@anandtiwarics, actually I see 2 issues here:

1) You mention a slightly incorrect variant of the URL, the correct one would be like 
https://vulners.com/api/v3/burp/software/?software=http&version=1.1&type=software
as we use not the full cpe, but just the software name. As you can see this request does not have any results indeed, and the results of the one you mention have no connection to Coyote (at least as far as I can see).

2) The actual request the script should have sent must be 
https://vulners.com/api/v3/burp/software/?software=cpe:/a:apache:coyote_http_connector:1.1&version=1.1&type=cpe
but for now I can not understand, why we do not see any results at all. I have conducted an experiment locally (just set this cpe on a port) and it worked as expected. 

Since you do not get any results for any of the ports the issue might be on your side. Could you please check you have access to vulners com server? And try using `--debug ` option to see whether you get any network errors during the scan.

**Pull request merged**
