### PR TITLE
Multiple fixes/enhancements

### PR DESCRIPTION
**Pull request by faichelbaum**

### CODE REVIEW

**Comment by faichelbaum** [comment]
Fix some glitches in the README.md
Update case for OpenVas to OpenVAS (matching official naming and case)
Enhanced OpenVAS settings form

**Comment by faichelbaum** [comment]
Added also  some status info for the webscanner and ipscan: it will display a message if no scanner is selected or that the scan started

**Comment by faichelbaum** [comment]
update ipscan table (fix display and add refresh info)

**Comment by anandtiwarics** [comment]
Really great work and thanks for contribution @faichelbaum I'll merge it after some test.

**Comment by faichelbaum** [comment]
No so great. Just familiarizing with your code to fix/enhance things step by step ;)

**Pull request merged**
